apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: book-service
  name: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: book-service
    spec:
      containers:
      - image: microservice-book:latest
        name: microservice-book
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: book-service
  name: book-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: book-service
  type: ClusterIP
status:
  loadBalancer: {}
